name: tall
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  local_auth: ^0.6.1
  font_awesome_flutter: ^8.4.0
  material_design_icons_flutter: 3.4.4895
  flappy_search_bar: 1.4.1
  share: ^0.6.2+5
  url_launcher: ^5.4.1
  pdf: ^1.5.0
  path_provider: ^1.6.5
  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  image_picker: ^0.6.1+4
  intl: ^0.16.1
  flutter_full_pdf_viewer: ^1.0.6
  # flutter_login: ^1.0.10+1
  # charts_flutter: ^0.8.1
  esys_flutter_share: ^1.0.2
  signature: ^3.0.0
  firebase_storage: ^3.1.5
  # contact_picker: ^0.0.2
  # native_contact_picker: ^0.0.6
  # screenshot_and_share: ^0.0.1
  http: ^0.12.0+4
  printing: ^3.3.1
  firebase_messaging: ^6.0.13

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Firebase dependencies
  firebase_auth: ^0.15.4
  google_sign_in: ^4.0.4
  cloud_firestore: ^0.13.0+1
  firebase_analytics: ^5.0.11
  # flutter_spinkit: "^4.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - graphics/rumi-gate.jpg
    - graphics/dataanalysis.png
    - assets/images/ledgers.png
    - assets/images/invoice.png
    - assets/images/invoice-maker.png

  fonts: 
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Bold.ttf
          weight: 500
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 300
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Proxima-Nova
      fonts: 
        - asset: fonts/proxima-nova-bold.ttf
          weight: 700
        - asset: fonts/proxima-nova-reg.ttf
          weight: 500
        - asset: fonts/proxima-nova-thin.ttf
          weight: 300


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
